export const BEGIN_FETCH = 'BEGIN_FETCH'

export const GET_SECRETS_SUCCESS = 'GET_SECRETS_SUCCESS'
export const GET_SECRETS_FAILURE = 'GET_SECRETS_FAILURE'

export const POST_SECRET_SUCCESS = 'POST_SECRET_SUCCESS'
export const POST_SECRET_FAILURE = 'POST_SECRET_FAILURE'